services:
    mysql:
        container_name: "mysql"
        image: mysql:8.0
        ports:
            - 3306:3306
            - 33060:33060
        volumes:
            - ./conf/oai_db2.sql:/docker-entrypoint-initdb.d/oai_db.sql
        environment:
            - TZ=Europe/Paris
            - MYSQL_DATABASE=oai_db
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
            - MYSQL_ROOT_PASSWORD=linux
        networks:
            public_net:
                ipv4_address:  ${MYSQL_IP:-192.168.70.131}
    oai-nssf:
        container_name: "oai-nssf"
        image: oaisoftwarealliance/oai-nssf:v2.1.0
        expose:
            - 80/tcp
            - 8080/tcp
        volumes:
            - ./conf/slicing_base_config.yaml:/openair-nssf/etc/config.yaml
            - ./conf/nssf_slice_config.yaml:/openair-nssf/etc/nssf_slice_config.yaml
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        cap_drop:
            - ALL
        privileged: true
        networks:
            public_net:
                ipv4_address: ${NSSF_IP:-192.168.70.132}
    oai-udr:
        container_name: "oai-udr"
        image: oaisoftwarealliance/oai-udr:v2.1.0
        expose:
            - 80/tcp
            - 8080/tcp
        volumes:
            - ./conf/slicing_base_config.yaml:/openair-udr/etc/config.yaml
        depends_on:
            - mysql
            - oai-nrf-slice12
        extra_hosts:
            - "mysql:192.168.70.131"
        networks:
            public_net:
                ipv4_address: ${UDR_IP:-192.168.70.133}
    oai-udm:
        container_name: "oai-udm"
        image: oaisoftwarealliance/oai-udm:v2.1.0
        expose:
            - 80/tcp
            - 8080/tcp
        volumes:
            - ./conf/slicing_base_config.yaml:/openair-udm/etc/config.yaml
        depends_on:
            - oai-udr
        networks:
            public_net:
                ipv4_address: ${UDM_IP:-192.168.70.134}
    oai-ausf:
        container_name: "oai-ausf"
        image: oaisoftwarealliance/oai-ausf:v2.1.0
        expose:
            - 80/tcp
            - 8080/tcp
        volumes:
            - ./conf/slicing_base_config.yaml:/openair-ausf/etc/config.yaml
        depends_on:
            - oai-udm
        networks:
            public_net:
                ipv4_address: ${AUSF_IP:-192.168.70.135}
    oai-nrf-slice12:
        container_name: "oai-nrf-slice12"
        image: oaisoftwarealliance/oai-nrf:v2.1.0
        expose:
            - 80/tcp
            - 8080/tcp
        volumes:
            - ./conf/slicing_slice1_config.yaml:/openair-nrf/etc/config.yaml
        networks:
            public_net:
              ipv4_address: ${NRF_IP:-192.168.70.136}
    oai-nrf-slice3:
        container_name: "oai-nrf-slice3"
        image: oaisoftwarealliance/oai-nrf:v2.1.0
        expose:
            - 80/tcp
            - 8080/tcp
        volumes:
            - ./conf/slicing_slice3_config.yaml:/openair-nrf/etc/config.yaml
        networks:
            public_net:
              ipv4_address: ${NRF3_IP:-192.168.70.137}
    oai-amf:
        container_name: "oai-amf"
        image: oaisoftwarealliance/oai-amf:v2.1.0
        expose:
            - 80/tcp
            - 8080/tcp
            - 38412/sctp
        volumes:
            - ./conf/slicing_base_config.yaml:/openair-amf/etc/config.yaml
        depends_on:
            - mysql
            - oai-ausf
            - oai-nrf-slice12
        extra_hosts:
            - "oai-nrf-slice12:192.168.70.136"
        networks:
            public_net:
                ipv4_address: ${AMF_IP:-192.168.70.138}
    oai-smf-slice1:
        container_name: "oai-smf-slice1"
        image: oaisoftwarealliance/oai-smf:v2.1.0
        expose:
            - 80/tcp
            - 8080/tcp
            - 8805/udp
        volumes:
            - ./conf/slicing_slice1_config.yaml:/openair-smf/etc/config.yaml
        depends_on:
            - oai-amf
            - oai-nrf-slice12
        networks:
            public_net:
                ipv4_address: ${SMF1_IP:-192.168.70.139}
    oai-smf-slice2:
        container_name: "oai-smf-slice2"
        image: oaisoftwarealliance/oai-smf:v2.1.0
        expose:
            - 80/tcp
            - 8080/tcp
            - 8805/udp
        volumes:
            - ./conf/slicing_slice2_config.yaml:/openair-smf/etc/config.yaml
        depends_on:
            - oai-amf
            - oai-nrf-slice12
        networks:
            public_net:
                ipv4_address: ${SMF2_IP:-192.168.70.140}
    oai-smf-slice3:
        container_name: "oai-smf-slice3"
        image: oaisoftwarealliance/oai-smf:v2.1.0
        expose:
            - 80/tcp
            - 8080/tcp
            - 8805/udp
        volumes:
            - ./conf/slicing_slice3_config.yaml:/openair-smf/etc/config.yaml
        depends_on:
            - oai-amf
            - oai-nrf-slice3
        networks:
            public_net:
                ipv4_address: ${SMF3_IP:-192.168.70.141}
    oai-upf-slice1:
        container_name: "oai-upf-slice1"
        image: oaisoftwarealliance/oai-upf:v2.1.0
        expose:
            - 2152/udp
            - 8805/udp
            - 8080/tcp
        volumes:
            - ./conf/slicing_slice1_config.yaml:/openair-upf/etc/config.yaml
        environment:
            - TZ=Europe/Paris
        depends_on:
            - oai-smf-slice1
            - oai-nrf-slice12
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        cap_drop:
            - ALL
        privileged: true
        networks:
            public_net:
                ipv4_address: ${UPF1_IP:-192.168.70.142}
    oai-upf-slice2:
        container_name: "oai-upf-slice2"
        image: oaisoftwarealliance/oai-upf:v2.1.0
        expose:
            - 2152/udp
            - 8805/udp
            - 8080/tcp
        volumes:
            - ./conf/slicing_slice2_config.yaml:/openair-upf/etc/config.yaml
        environment:
            - TZ=Europe/Paris
        depends_on:
            - oai-smf-slice2
            - oai-nrf-slice12
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        cap_drop:
            - ALL
        privileged: true
        networks:
            public_net:
                ipv4_address: ${UPF2_IP:-192.168.70.143}
    oai-upf-slice3:
        container_name: "oai-upf-slice3"
        image: oaisoftwarealliance/oai-upf:v2.1.0
        expose:
            - 2152/udp
            - 8805/udp
            - 8080/tcp
        volumes:
            - ./conf/slicing_slice3_config.yaml:/openair-upf/etc/config.yaml
        environment:
            - TZ=Europe/Paris
        depends_on:
            - oai-nrf-slice3
            - oai-smf-slice3
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        cap_drop:
            - ALL
        privileged: true
        networks:
            public_net:
                ipv4_address: ${UPF3_IP:-192.168.70.144}
    oai_ext_dn:
        image: oaisoftwarealliance/trf-gen-cn5g:latest
        privileged: true
        init: true
        container_name: oai-ext-dn
        entrypoint: /bin/bash -c \
              "iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE;"\
              "ip route add 12.2.1.0/25 via 192.168.70.142 dev eth0;"\
              "ip route add 12.1.1.128/26 via 192.168.70.143 dev eth0;"\
              "ip route add 12.1.1.192/26 via 192.168.70.144 dev eth0;"\
              "ip route; sleep infinity"
        command: ["/bin/bash", "-c", "trap : SIGTERM SIGINT; sleep infinity & wait"]
        healthcheck:
            test: /bin/bash -c "iptables -L -t nat | grep MASQUERADE"
            interval: 10s
            timeout: 5s
            retries: 10
        networks:
            public_net:
                ipv4_address: ${EXTDN_IP:-192.168.70.145}
            public_net_core:
                ipv4_address: ${EXTDN_CN_IP:-192.168.73.145}

networks:
    public_net:
        driver: bridge
        name: demo-oai-public-net
        ipam:
            config:
                - subnet: ${PUBLICNET_SUBNET:-192.168.70.0/24}
        driver_opts:
            com.docker.network.bridge.name: "demo-oai"
    public_net_access:
        name: oai-public-access
        ipam:
            config:
              - subnet: ${ACCESS_SUBNET:-192.168.72.0/24}
        driver_opts:
            com.docker.network.bridge.name: "cn5g-access"
    public_net_core:
        name: oai-public-core
        ipam:
            config:
              - subnet: ${CN_SUBNET:-192.168.73.0/24}
        driver_opts:
            com.docker.network.bridge.name: "cn5g-core"
