# Reference:- TS 29.531 R16.0.0., Section- 6.1.6 Data Model 
info:
  version: 1.4.0
  description: OAI-NSSF Release v1.4.0
configuration:
  nsiInfoList:
    - snssai:
        sst: 128
        sd: '000080'
      nsiInformationList:
        nrfId: http://192.168.70.136:8080/nnrf-disc/v1/nf-instances
        nsiId: '11'
    - snssai:
        sst: 1
        sd: '000001'
      nsiInformationList:
        nrfId: http://192.168.70.136:8080/nnrf-disc/v1/nf-instances
        nsiId: '12'
    - snssai:
        sst: 5
        sd: '000082'
      nsiInformationList:
        nrfId: http://192.168.70.137:8080/nnrf-disc/v1/nf-instances
        nsiId: '12'
    - snssai:
        sst: 128
        sd: '128'
      nsiInformationList:
        nrfId: http://oai-cn5g-nrf-10.fr:8080/nnrf-disc/v1/nf-instances
        nsiId: '11'
    - snssai:
        sst: 128
        sd: '130'
      nsiInformationList:
        nrfId: http://oai-cn5g-nrf-20.fr:8080/nnrf-disc/v1/nf-instances
        nsiId: '20'
        nrfNfMgtUri: http://oai-cn5g-nrf-10.fr:8080/nnrf-nfm/v1/nf-instances
    - snssai:
        sst: 5
        sd: '130'
      nsiInformationList:
        nrfId: http://oai-cn5g-nrf-20.fr:8080/nnrf-disc/v1/nf-instances
        nsiId: '20'
    - snssai:
        sst: 132
        sd: '132'
      nsiInformationList:
        nrfId: http://oai-cn5g-nrf-20.fr:8080/nnrf-disc/v1/nf-instances
        nsiId: '20'
    - snssai:
        sst: 133
      nsiInformationList:
        nrfId: http://oai-cn5g-nrf-20.fr:8080/nnrf-disc/v1/nf-instances
        nsiId: '20'
  taInfoList:
    - tai:
        plmnId:
          mcc: '001'
          mnc: '01'
        tac: '1'
      supportedSnssaiList:
      - sst: 1
        sd: '1'
      - sst: 128
        sd: '128'
      - sst: 128
        sd: '130'
      - sst: 5
        sd: '130'
  amfInfoList:
    - targetAmfSet: oai5gcn.mcc001.mnc01.regionid128.setid1.3gppnetwork.org
      nrfAmfSet: http://oai-cn5g-nrf.fr:8080/nnrf-disc/v1/nf-instances'
      nrfAmfSetNfMgtUri: http://oai-cn5g-nrf.fr:8080/nnrf-nfm/v1/nf-instances
      amfList:
        - nfId: 405e8251-cc5a-45dd-a494-efb9eaf1cd58
          supportedNssaiAvailabilityData:
              tai:
                plmnId:
                  mcc: 001
                  mnc: 01
                tac: 1
              supportedSnssaiList:
                - sst: 128
                  sd: 128
                - sst: 1
                  sd: 1
                - sst: 128
                  sd: 130
                - sst: 5
                  sd: 130
        - nfId: 405e8251-cc5a-45dd-a494-efb9eaf1cd68
          supportedNssaiAvailabilityData:
              tai:
                plmnId:
                  mcc: 001
                  mnc: 01
                tac: 1
              supportedSnssaiList:
                - sst: 128
                  sd: 130
                - sst: 128
                  sd: 128
                - sst: 1
                  sd: 1
                - sst: 5
                  sd: 130
              taiList:
                - tai:
                    plmnId:
                      mcc: 001
                      mnc: 01
                    tac: 1
                  supportedSnssaiList:
                    - sst: 5
                      sd: 130
    - targetAmfSet: oai5gcn.mcc001.mnc01.regionid128.setid2.3gppnetwork.org
      nrfAmfSet: http://oai-cn5g-nrf.fr:8080/nnrf-disc/v1/nf-instances
      nrfAmfSetNfMgtUri: http://oai-cn5g-nrf.fr:8080/nnrf-nfm/v1/nf-instances
      amfList:
        - nfId: 405e8251-cc5a-45dd-a494-efb9eaf1cd78
          supportedNssaiAvailabilityData:
              tai:
                plmnId:
                  mcc: 001
                  mnc: 01
                tac: 1
              supportedSnssaiList:
                - sst: 5
                  sd: 130
